### ISSUE TITLE
Reference to your project

### ISSUE THREAD

**Issue by charlysan** [rdoetjes/tuts#6]
Your channel and repository are great.

I just wanted to check if it's okay with you that I included a reference to your LPT DAC Project in [my work](https://github.com/charlysan/jalptdac?tab=readme-ov-file#references).

Thanks.

**Comment by rdoetjes** [comment]
Hi,Sure and cool!!! Its for everyone to use but very decent of you to ask.Thanks!RaySent from my iPhoneOn 25 Jan 2024, at 15:08, charlysan ***@***.***> wrote:﻿
Your channel and repository are great.
I just wanted to check if it's okay with you that I included a reference to your LPT DAC Project in my work.
Thanks.
